/* export const productTypes = [
  "Aromatisert vin",
  "Brennevin",
  "Fruktvin",
  "Hvitvin",
  "Mjød",
  "Musserende vin",
  "Perlende vin",
  "Rosévin",
  "Rødvin",
  "Sake",
  "Sider",
  "Sterkvin",
  "Øl",
];
*/

export const productTypes =  [
  "Akevitt",
  "Portvin",
  "Vodka",
  "Druebrennevin",
  "Whisky",
  "Likør",
  "Genever",
  "Gin",
  "Bitter",
  "Fruktbrennevin",
  "Vermut",
  "Aromatisert vin",
  "Brennevin, annet",
  "Sherry",
  "Rødvin",
  "Hvitvin",
  "Perlende vin, rosé",
  "Rosévin",
  "Champagne, brut",
  "Champagne, sec",
  "Musserende vin, rosé",
  "Champagne, rosé",
  "Musserende vin",
  "Perlende vin, rød",
  "Porter & stout",
  "Perlende vin, hvit",
  "Rom",
  "Klosterstil",
  "India pale ale",
  "Spesial",
  "Mørk lager",
  "Saison farmhouse ale",
  "Hveteøl",
  "Pale ale",
  "Lys ale",
  "Sterkvin, annen",
  "Barley wine",
  "Fruktvin",
  "Sider",
  "Lys lager",
  "Brown ale",
  "Alkoholfri musserende drikk",
  "Champagne extra brut",
  "Sake",
  "Surøl",
  "Madeira",
  "Alkoholfritt øl",
  "Red/amber",
  "Mjød",
  "Brennevin, nøytralt < 37,5 %",
  "Champagne, annen",
  "Scotch ale",
  "Alkoholfri vin",
].sort();
